#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES : mise en ligne de https://cmdbaby.app (#112).
# Usage : scripts/setup-site.sh [N]   — reprend à l'étape N après une interruption.
# Aucun identifiant ni adresse personnelle n'est écrit, ni dans le dépôt ni ailleurs.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12
START="${1:-1}"
DOMAIN="cmdbaby.app"
DASH="https://dash.cloudflare.com/"

cd "$(dirname "$0")/.."

wrangler() { npm exec --prefix site -- wrangler "$@"; }

# dig_short TYPE NOM : réponses DNS via le résolveur de Cloudflare.
dig_short() { dig +short "$1" "$2" @1.1.1.1 2>/dev/null || true; }

# curl_cf NOM [options…] URL : curl en résolvant NOM par 1.1.1.1. Le cache DNS du Mac
# (ou d'un VPN) peut garder un « nom inconnu » longtemps après la création du domaine.
curl_cf() {
  local host="$1" ip
  shift
  ip=$(dig_short A "$host" | grep -E '^[0-9.]+$' | head -n1)
  if [[ -n "$ip" ]]; then
    curl --resolve "$host:443:$ip" "$@"
  else
    curl "$@"
  fi
}

site_is_up() { curl_cf "$DOMAIN" -fsI "https://$DOMAIN/" >/dev/null 2>&1; }

yes_or_stop() {
  # yes_or_stop "question" "ce qu'il faut faire sinon"
  if ! confirm "$1"; then
    printf '\n'; warn "$2"
    note "Relancer ensuite : scripts/setup-site.sh $_STAGE_INDEX"
    exit 1
  fi
}

ACCOUNT_NAME="?"
WWW_STATE="non vérifié"
MAIL_STATE="non vérifié"

stage_node() {
  stage "Node.js"
  if command -v npx >/dev/null 2>&1; then
    say "Node.js est présent ($(node --version)). Rien à faire."
    return
  fi
  warn "npx est introuvable."
  say "Wrangler, l'outil de Cloudflare, s'installe avec Node.js."
  if confirm "Lancer « brew install node » maintenant ?"; then
    brew install node
  fi
  command -v npx >/dev/null 2>&1 || { warn "Installer Node.js (brew install node), puis relancer."; exit 1; }
}

stage_wrangler() {
  stage "Connexion de Wrangler à Cloudflare"
  say "Installation de la version de Wrangler épinglée dans site/…"
  npm ci --prefix site --ignore-scripts --no-audit --no-fund >/dev/null
  local who
  who=$(wrangler whoami 2>&1 || true)
  if grep -qi "not authenticated" <<<"$who"; then
    say "Personne n'est connecté. Wrangler va ouvrir le navigateur pour autoriser l'accès."
    pause "Entrée pour lancer « wrangler login »"
    wrangler login
    who=$(wrangler whoami 2>&1 || true)
  fi
  if grep -qi "not authenticated" <<<"$who"; then
    warn "Wrangler n'est toujours pas connecté. Relancer cette étape."
    exit 1
  fi
  printf '%s\n' "$who" | grep -E "│|Account|email" | sed 's/^/    /' || true
  ACCOUNT_NAME=$(printf '%s\n' "$who" | grep -E "│" | grep -v "Account Name" | head -n1 | awk -F'│' '{gsub(/^ +| +$/,"",$2); print $2}')
  [[ -n "$ACCOUNT_NAME" ]] || ACCOUNT_NAME="(voir ci-dessus)"
  if (( $(printf '%s\n' "$who" | grep -cE "│ .* │ [0-9a-f]{32} │") > 1 )) && [[ -z "${CLOUDFLARE_ACCOUNT_ID:-}" ]]; then
    warn "Plusieurs comptes Cloudflare sont visibles."
    say "Choisir celui où cmdbaby.app est enregistré, puis :"
    say "  export CLOUDFLARE_ACCOUNT_ID=<id du compte>"
    say "  scripts/setup-site.sh 2"
    exit 1
  fi
  note "Le jeton de « wrangler login » reste sur ce Mac. Ne jamais le copier ailleurs."
}

stage_2fa() {
  stage "Sécurité du compte Cloudflare"
  say "Le compte Cloudflare contrôle le domaine, le site et l'adresse support."
  say "Il doit être protégé par une clé de sécurité ou une clé d'accès (passkey)."
  open_url "https://dash.cloudflare.com/profile/authentication"
  step "My Profile › Authentication : ajouter une clé de sécurité ou une clé d'accès."
  step "Garder les codes de secours en lieu sûr, hors de ce dépôt."
  yes_or_stop "La 2FA par clé est-elle active ?" "Activer la 2FA par clé avant de continuer."
}

stage_domain() {
  stage "Domaine $DOMAIN"
  open_url "$DASH"
  step "Domain Registration › Manage Domains : $DOMAIN doit être « Active »."
  yes_or_stop "$DOMAIN apparaît-il comme Active ?" "Le domaine doit être actif chez Cloudflare (Domain Registration)."
  step "Dans la fiche du domaine (Manage) : « Registrar lock » activé."
  step "Au même endroit : renouvellement automatique (Auto-renew) activé."
  yes_or_stop "Le verrou du registrar et le renouvellement automatique sont-ils activés ?" \
    "Activer le verrou et le renouvellement automatique : sans eux, le domaine peut être transféré ou expirer."
}

stage_dns() {
  stage "Enregistrements DNS existants"
  if site_is_up; then
    say "https://$DOMAIN répond déjà : le domaine personnalisé du Worker est en place."
    return
  fi
  say "Le Worker crée lui-même l'enregistrement de $DOMAIN."
  say "Il échoue si un enregistrement A, AAAA ou CNAME existe déjà sur $DOMAIN (par exemple une page de parking)."
  local current
  current=$(dig_short A "$DOMAIN")
  [[ -n "$current" ]] && note "Réponse DNS actuelle pour $DOMAIN : $(tr '\n' ' ' <<<"$current")"
  open_url "$DASH"
  step "Ouvrir $DOMAIN › DNS › Records."
  step "Supprimer tout enregistrement A, AAAA ou CNAME dont le nom est « $DOMAIN » ou « @ »."
  step "Ne pas toucher aux MX ni aux TXT."
  yes_or_stop "Ces enregistrements sont-ils supprimés ou absents ?" "Les supprimer, sinon le premier déploiement échouera."
}

stage_deploy() {
  stage "Premier déploiement"
  if site_is_up; then
    say "https://$DOMAIN répond déjà. Rien à faire."
    return
  fi
  confirm "Déployer le site maintenant (scripts/deploy-site.sh) ?" || { warn "Déploiement annulé."; exit 1; }
  scripts/deploy-site.sh
  say "Attente du certificat : jusqu'à 5 minutes, un essai toutes les 15 secondes…"
  for _ in $(seq 1 20); do
    if site_is_up; then
      say "${GREEN}✓${RESET} https://$DOMAIN répond."
      return
    fi
    sleep 15
  done
  warn "https://$DOMAIN ne répond toujours pas. Vérifier Workers & Pages › cmdbaby-site › Settings › Domains, puis relancer cette étape."
  exit 1
}

www_redirects() {
  local headers
  headers=$(curl_cf "www.$DOMAIN" -sI "https://www.$DOMAIN/" 2>/dev/null || true)
  grep -qE "^HTTP/[0-9.]+ 301" <<<"$headers" && grep -qiE "^location: https://$DOMAIN/" <<<"$headers"
}

stage_www() {
  stage "Redirection de www.$DOMAIN"
  if www_redirects; then
    say "www.$DOMAIN redirige déjà vers https://$DOMAIN/. Rien à faire."
    WWW_STATE="redirige vers https://$DOMAIN/"
    return
  fi
  if ! confirm "Faire rediriger www.$DOMAIN vers https://$DOMAIN (recommandé) ?"; then
    WWW_STATE="non configuré (choix)"
    return
  fi
  open_url "$DASH"
  step "$DOMAIN › DNS › Records › Add record : type AAAA, nom « www », adresse « 100:: », Proxied (nuage orange)."
  step "$DOMAIN › Rules › Redirect Rules › Create : choisir le modèle « Redirect from WWW to root »."
  pause "Entrée une fois la règle enregistrée"
  say "Vérification (quelques secondes peuvent être nécessaires)…"
  for _ in $(seq 1 8); do
    if www_redirects; then
      say "${GREEN}✓${RESET} www.$DOMAIN redirige en 301 vers https://$DOMAIN/."
      WWW_STATE="redirige vers https://$DOMAIN/"
      return
    fi
    sleep 15
  done
  warn "La redirection ne répond pas encore. Vérifier la règle, puis relancer : scripts/setup-site.sh $_STAGE_INDEX"
  exit 1
}

stage_mail() {
  stage "Adresse support@$DOMAIN"
  if dig_short MX "$DOMAIN" | grep -q "mx.cloudflare.net"; then
    say "Email Routing est déjà actif (MX Cloudflare présents)."
  else
    say "La page Support affiche support@$DOMAIN. Cloudflare Email Routing la transfère vers votre boîte."
    open_url "$DASH"
    step "$DOMAIN › Email › Email Routing : activer, en acceptant les enregistrements MX et SPF proposés."
    step "Destination addresses : ajouter votre adresse personnelle, puis la confirmer depuis l'e-mail reçu."
    note "Cette adresse n'est demandée ni écrite par ce script."
    step "Routing rules › Custom address : « support » → votre adresse."
    pause "Entrée une fois la règle créée"
  fi
  step "Envoyer un e-mail de test à support@$DOMAIN depuis une autre adresse."
  if confirm "L'e-mail de test est-il bien arrivé ?"; then
    MAIL_STATE="support@$DOMAIN reçu"
  else
    warn "Vérifier la règle de routage et la confirmation de l'adresse de destination."
    note "Relancer ensuite : scripts/setup-site.sh $_STAGE_INDEX"
    exit 1
  fi
}

stage_dmarc() {
  stage "Anti-usurpation de l'adresse (DMARC)"
  say "Le domaine n'envoie aucun e-mail. Un DMARC « reject » empêche d'envoyer en se faisant passer pour support@$DOMAIN."
  if dig_short TXT "_dmarc.$DOMAIN" | grep -q "p=reject"; then
    say "DMARC p=reject est déjà publié. Rien à faire."
  else
    open_url "$DASH"
    step "$DOMAIN › DNS › Records › Add record : type TXT, nom « _dmarc »,"
    step "contenu : v=DMARC1; p=reject; adkim=s; aspf=s"
    step "Garder l'enregistrement SPF ajouté par Email Routing."
    pause "Entrée une fois l'enregistrement ajouté"
    dig_short TXT "_dmarc.$DOMAIN" | grep -q "p=reject" \
      || { warn "_dmarc.$DOMAIN ne montre pas encore p=reject. Attendre une minute puis relancer : scripts/setup-site.sh $_STAGE_INDEX"; exit 1; }
    say "${GREEN}✓${RESET} DMARC p=reject publié."
  fi
  dig_short TXT "$DOMAIN" | grep -q "v=spf1" || warn "Aucun SPF sur $DOMAIN : réactiver les enregistrements proposés par Email Routing."
}

dnssec_validated() { dig +dnssec "$DOMAIN" @1.1.1.1 2>/dev/null | grep -qE "flags:[^;]* ad[ ;]"; }

stage_dnssec() {
  stage "DNSSEC"
  if dnssec_validated; then
    say "DNSSEC est actif et validé. Rien à faire."
    return
  fi
  say "DNSSEC signe les réponses DNS : personne ne peut détourner $DOMAIN vers un autre serveur."
  open_url "$DASH"
  step "$DOMAIN › DNS › Settings › DNSSEC : Enable."
  note "Le domaine étant chez Cloudflare Registrar, l'enregistrement DS est publié automatiquement."
  pause "Entrée une fois DNSSEC activé"
  say "Vérification : la propagation peut prendre de quelques minutes à une heure."
  if dnssec_validated; then
    say "${GREEN}✓${RESET} DNSSEC validé."
  else
    warn "Pas encore validé. Relancer plus tard : scripts/setup-site.sh $_STAGE_INDEX"
    exit 1
  fi
}

stage_caa() {
  stage "Autorités de certification (CAA)"
  say "Les enregistrements CAA limitent qui peut émettre un certificat pour $DOMAIN."
  local caa
  caa=$(dig_short CAA "$DOMAIN")
  if grep -q "iodef" <<<"$caa" && grep -q "issue" <<<"$caa"; then
    say "Des CAA sont déjà publiés :"
    sed 's/^/    /' <<<"$caa"
  else
    open_url "https://developers.cloudflare.com/ssl/edge-certificates/caa-records/"
    step "Lire sur cette page quelles autorités Cloudflare utilise (par exemple letsencrypt.org, pki.goog, ssl.com)."
    open_url "$DASH"
    step "$DOMAIN › DNS › Records : pour chacune, un enregistrement CAA, flag 0, tag « issue », valeur = l'autorité."
    step "Puis un CAA flag 0, tag « iodef », valeur « mailto:support@$DOMAIN »."
    pause "Entrée une fois les CAA ajoutés"
    caa=$(dig_short CAA "$DOMAIN")
    grep -q "issue" <<<"$caa" || { warn "Aucun CAA « issue » visible. Attendre une minute puis relancer : scripts/setup-site.sh $_STAGE_INDEX"; exit 1; }
    sed 's/^/    /' <<<"$caa"
  fi
  if site_is_up; then
    say "${GREEN}✓${RESET} https://$DOMAIN répond toujours."
  else
    warn "https://$DOMAIN ne répond plus : vérifier que les CAA autorisent bien les autorités de Cloudflare."
    exit 1
  fi
  note "Le certificat se renouvelle tout seul ; revérifier son émetteur dans quelques mois (SSL/TLS › Edge Certificates)."
}

stage_summary() {
  stage "Résumé"
  say "Compte Cloudflare : $ACCOUNT_NAME"
  say "Site : https://$DOMAIN $(site_is_up && echo '(répond)' || echo '(ne répond pas)')"
  say "www : $WWW_STATE"
  say "E-mail : $MAIL_STATE"
  say "DNSSEC : $(dnssec_validated && echo 'validé' || echo 'non validé')"
  say "DMARC : $(dig_short TXT "_dmarc.$DOMAIN" | grep -q 'p=reject' && echo 'p=reject' || echo 'absent')"
  say "CAA : $(dig_short CAA "$DOMAIN" | grep -c issue) autorité(s) autorisée(s)"
  pause "Entrée pour terminer"
}

STAGES=(stage_node stage_wrangler stage_2fa stage_domain stage_dns stage_deploy stage_www stage_mail stage_dmarc stage_dnssec stage_caa stage_summary)

if ! [[ "$START" =~ ^[0-9]+$ ]] || (( START < 1 || START > TOTAL_STAGES )); then
  printf 'Étape inconnue : %s (1 à %s)\n' "$START" "$TOTAL_STAGES" >&2
  exit 1
fi

banner "Mise en ligne de https://$DOMAIN"

for (( n = START; n <= TOTAL_STAGES; n++ )); do
  _STAGE_INDEX=$((n - 1))
  "${STAGES[$((n - 1))]}"
  if (( n < TOTAL_STAGES )); then pause "Entrée pour l'étape suivante"; fi
done

finish
