#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES : identifiants de publication (#98). À lancer une fois, sur le Mac du mainteneur.
# Usage : scripts/setup-release.sh [N]   — reprend à l'étape N après une interruption.
# N'écrit que des valeurs publiques dans scripts/release.env : Team ID, nom du profil
# notarytool, clé publique Sparkle. Aucun secret n'est écrit ni affiché.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
START="${1:-1}"

cd "$(dirname "$0")/.."
ENV_FILE="scripts/release.env"

SPARKLE_VERSION="2.10.0"
# Empreinte de Sparkle-2.10.0.tar.xz, recoupée avec le digest de l'API GitHub.
SPARKLE_SHA256="c2bf58aa8387266ac179357b1415d6f2635f044da8be41042af32425dae6da0c"
TOOLS_DIR="$HOME/Library/Application Support/cmdbaby-release-tools/sparkle-$SPARKLE_VERSION"
GENERATE_KEYS="$TOOLS_DIR/bin/generate_keys"

stop() {
  printf '\n'; warn "$1"
  note "Relancer ensuite : scripts/setup-release.sh $_STAGE_INDEX"
  exit 1
}

yes_or_stop() { confirm "$1" || stop "$2"; }

stage_accounts() {
  stage "Mac et comptes"
  if fdesetup status 2>/dev/null | grep -q "FileVault is On"; then
    say "${GREEN}✓${RESET} FileVault est activé."
  else
    open_url "x-apple.systempreferences:com.apple.preference.security?FileVault"
    stop "FileVault est désactivé : l'activer (Réglages Système › Confidentialité et sécurité › FileVault). Ce Mac signe les versions."
  fi
  open_url "https://account.apple.com/account/manage"
  yes_or_stop "La double authentification est-elle active sur le compte Apple ?" \
    "Activer la double authentification du compte Apple avant de continuer."
  open_url "https://github.com/settings/security"
  yes_or_stop "Le compte GitHub a-t-il une clé d'accès (passkey) ou une clé de sécurité ?" \
    "Ajouter une clé d'accès ou une clé de sécurité à GitHub (Settings › Password and authentication)."
}

stage_developer_program() {
  stage "Compte Apple Developer"
  say "La signature Developer ID et la notarisation demandent l'Apple Developer Program payant."
  open_url "https://developer.apple.com/account"
  yes_or_stop "L'adhésion apparaît-elle comme active ?" \
    "Attendre l'activation de l'adhésion (Membership details › Active), puis relancer."
}

developer_id_line() {
  security find-identity -v -p codesigning 2>/dev/null | grep "Developer ID Application" | head -n1 || true
}

stage_certificate() {
  stage "Certificat Developer ID Application"
  local line
  line=$(developer_id_line)
  if [[ -z "$line" ]]; then
    say "Créer le certificat depuis Xcode :"
    step "Xcode › Settings › Accounts › (votre compte) › Manage Certificates…"
    step "« + » › Developer ID Application."
    note "Ou sur developer.apple.com › Certificates, puis l'installer dans le trousseau."
    open_url "https://developer.apple.com/account/resources/certificates/list"
    pause "Entrée une fois le certificat installé"
    line=$(developer_id_line)
    [[ -n "$line" ]] || stop "Aucune identité « Developer ID Application » dans le trousseau."
  fi
  RELEASE_TEAM_ID=$(sed -E 's/.*\(([A-Z0-9]{10})\)".*/\1/' <<<"$line")
  [[ "$RELEASE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] || stop "Team ID illisible dans l'identité trouvée."
  say "${GREEN}✓${RESET} Identité Developer ID trouvée, Team ID : $RELEASE_TEAM_ID"
  write_env RELEASE_TEAM_ID "$RELEASE_TEAM_ID"
}

stage_certificate_backup() {
  stage "Sauvegarde du certificat"
  say "Sans sauvegarde, un Mac perdu oblige à créer un nouveau certificat."
  if confirm "Le certificat est-il déjà sauvegardé hors ligne en .p12 chiffré ?"; then
    return
  fi
  step "Ouvrir Trousseau d'accès › session › Mes certificats."
  step "Clic droit sur « Developer ID Application: … » › Exporter… › format .p12, avec un mot de passe solide."
  step "Enregistrer le fichier HORS de ce dépôt, puis le ranger hors ligne (clé USB chiffrée, gestionnaire de mots de passe)."
  open -a "Keychain Access" >/dev/null 2>&1 || true
  pause "Entrée une fois l'export rangé"
  if find . -name '*.p12' -not -path './.build/*' | grep -q .; then
    stop "Un fichier .p12 se trouve dans le dépôt : le déplacer hors du dépôt."
  fi
  yes_or_stop "Le .p12 est-il rangé hors ligne ?" "Ranger le .p12 hors ligne avant de continuer."
}

notary_ok() { xcrun notarytool history --keychain-profile "$RELEASE_NOTARY_PROFILE" >/dev/null 2>&1; }

stage_notary() {
  stage "Profil de notarisation"
  RELEASE_TEAM_ID=$(_existing RELEASE_TEAM_ID || true)
  [[ -n "$RELEASE_TEAM_ID" ]] || stop "Team ID inconnu : relancer à partir de l'étape 3."
  RELEASE_NOTARY_PROFILE=$(_existing RELEASE_NOTARY_PROFILE || echo "cmdbaby-notary")
  if notary_ok; then
    say "${GREEN}✓${RESET} Le profil « $RELEASE_NOTARY_PROFILE » fonctionne déjà."
    write_env RELEASE_NOTARY_PROFILE "$RELEASE_NOTARY_PROFILE"
    return
  fi
  say "notarytool garde ses identifiants dans le trousseau, sous un nom de profil."
  open_url "https://account.apple.com/account/manage"
  step "Connexion et sécurité › Mots de passe pour app › créer « cmdbaby-notary »."
  note "Gardez ce mot de passe affiché : notarytool va le demander. Ce script ne le lit pas."
  local apple_id
  printf '  %sIdentifiant Apple (e-mail) :%s ' "$BOLD" "$RESET"
  read -r apple_id || true
  [[ -n "$apple_id" ]] || stop "Identifiant Apple vide."
  xcrun notarytool store-credentials "$RELEASE_NOTARY_PROFILE" --apple-id "$apple_id" --team-id "$RELEASE_TEAM_ID"
  notary_ok || stop "« notarytool history » échoue avec ce profil : vérifier le mot de passe d'app."
  say "${GREEN}✓${RESET} Profil « $RELEASE_NOTARY_PROFILE » enregistré et vérifié."
  write_env RELEASE_NOTARY_PROFILE "$RELEASE_NOTARY_PROFILE"
}

stage_sparkle_tools() {
  stage "Outils Sparkle $SPARKLE_VERSION"
  if [[ -x "$GENERATE_KEYS" ]]; then
    say "Les outils Sparkle sont déjà installés."
    return
  fi
  local archive actual
  archive=$(mktemp "${TMPDIR:-/tmp}/sparkle.XXXXXX")
  say "Téléchargement de Sparkle-$SPARKLE_VERSION.tar.xz…"
  curl -fsSL -o "$archive" \
    "https://github.com/sparkle-project/Sparkle/releases/download/$SPARKLE_VERSION/Sparkle-$SPARKLE_VERSION.tar.xz"
  actual=$(shasum -a 256 "$archive" | awk '{print $1}')
  if [[ "$actual" != "$SPARKLE_SHA256" ]]; then
    rm -f "$archive"
    stop "Empreinte SHA-256 inattendue pour Sparkle ($actual) : rien n'a été extrait."
  fi
  mkdir -p "$TOOLS_DIR"
  tar -xJf "$archive" -C "$TOOLS_DIR" ./bin
  rm -f "$archive"
  [[ -x "$GENERATE_KEYS" ]] || stop "generate_keys introuvable après extraction."
  say "${GREEN}✓${RESET} Outils vérifiés et extraits hors du dépôt."
}

stage_sparkle_key() {
  stage "Clé Sparkle EdDSA"
  [[ -x "$GENERATE_KEYS" ]] || stop "Outils Sparkle absents : relancer à partir de l'étape 6."
  local public
  # Une clé publique Ed25519 en base64 : 44 caractères. generate_keys -p écrit ses erreurs sur stdout.
  public=$("$GENERATE_KEYS" -p 2>/dev/null || true)
  if ! [[ "$public" =~ ^[A-Za-z0-9+/]{43}=$ ]]; then
    confirm "Aucune clé Sparkle dans le trousseau. La créer maintenant ?" || stop "Clé Sparkle non créée."
    "$GENERATE_KEYS" >/dev/null
    public=$("$GENERATE_KEYS" -p 2>/dev/null || true)
    [[ "$public" =~ ^[A-Za-z0-9+/]{43}=$ ]] || stop "generate_keys n'a pas produit de clé publique lisible."
  fi
  say "Clé publique (à mettre dans l'Info.plist, clé SUPublicEDKey, par #102) :"
  say "  ${BOLD}$public${RESET}"
  write_env SPARKLE_PUBLIC_KEY "$public"
}

stage_sparkle_backup() {
  stage "Sauvegarde de la clé Sparkle"
  say "Perdre la clé privée rend toute mise à jour impossible pour les utilisateurs existants."
  if confirm "La clé privée Sparkle est-elle déjà sauvegardée hors de ce Mac ?"; then
    return
  fi
  local export_file
  export_file=$(mktemp "${TMPDIR:-/tmp}/cmdbaby-sparkle-key.XXXXXX")
  rm -f "$export_file"
  "$GENERATE_KEYS" -x "$export_file"
  say "Clé privée exportée dans : $export_file"
  step "Ranger ce fichier (ou son contenu) dans votre gestionnaire de mots de passe."
  note "Jamais dans le dépôt, un ticket, un chat ou un journal."
  pause "Entrée une fois la clé rangée : le fichier sera effacé"
  rm -P "$export_file"
  [[ ! -e "$export_file" ]] || stop "Le fichier d'export existe encore : l'effacer à la main ($export_file)."
  pbcopy </dev/null 2>/dev/null || true
  say "${GREEN}✓${RESET} Fichier d'export effacé, presse-papiers vidé."
}

stage_git_signing() {
  stage "Signature des commits et des tags"
  if [[ "$(git config --get gpg.format || true)" != "ssh" || -z "$(git config --get user.signingkey || true)" ]]; then
    say "Configurer la signature SSH :"
    step "git config --global gpg.format ssh"
    step "git config --global user.signingkey ~/.ssh/<clé>.pub"
    stop "Signature SSH non configurée."
  fi
  for key in commit.gpgsign tag.gpgsign; do
    if [[ "$(git config --get "$key" || true)" != "true" ]]; then
      confirm "Activer $key pour tous les dépôts ?" && git config --global "$key" true
    fi
  done
  if command -v gh >/dev/null 2>&1 && ! gh ssh-key list 2>/dev/null | grep -q "signing"; then
    warn "Aucune clé de signature visible sur GitHub (ou droit gh manquant)."
    step "gh ssh-key add $(git config --get user.signingkey) --type signing --title cmdbaby-signing"
    pause "Entrée une fois la clé ajoutée (ou si elle l'est déjà)"
  fi
  local tag="test-signature-$$"
  git tag -s "$tag" -m test >/dev/null
  if git tag -v "$tag" >/dev/null 2>&1; then
    git tag -d "$tag" >/dev/null
    say "${GREEN}✓${RESET} Un tag signé se vérifie (git tag -v)."
  else
    git tag -d "$tag" >/dev/null
    stop "git tag -v échoue : configurer gpg.ssh.allowedSignersFile avec votre clé."
  fi
}

stage_summary() {
  stage "Résumé"
  say "Identité : $(developer_id_line | sed -E 's/.*"(.*)".*/\1/')"
  say "Team ID : $(_existing RELEASE_TEAM_ID || echo '?')"
  say "Profil notarytool : $(_existing RELEASE_NOTARY_PROFILE || echo '?')"
  say "Clé publique Sparkle : $(_existing SPARKLE_PUBLIC_KEY || echo '?')"
  note "scripts/release.env ne contient que ces valeurs publiques."
  note "Ne jamais committer de secret : .p12, clé privée Sparkle, mot de passe d'app."
  pause "Entrée pour terminer"
}

STAGES=(stage_accounts stage_developer_program stage_certificate stage_certificate_backup stage_notary
  stage_sparkle_tools stage_sparkle_key stage_sparkle_backup stage_git_signing stage_summary)

if ! [[ "$START" =~ ^[0-9]+$ ]] || (( START < 1 || START > TOTAL_STAGES )); then
  printf 'Étape inconnue : %s (1 à %s)\n' "$START" "$TOTAL_STAGES" >&2
  exit 1
fi

banner "Identifiants de publication de CmdBaby"

for (( n = START; n <= TOTAL_STAGES; n++ )); do
  _STAGE_INDEX=$((n - 1))
  "${STAGES[$((n - 1))]}"
  if (( n < TOTAL_STAGES )); then pause "Entrée pour l'étape suivante"; fi
done

finish
